(wip) Broken! Again multiple dataloaders in pl_module. It needs to handle dataloader_idx properly
And tried CombinedDataloader but:

    Exception has occurred: ValueError
    `trainer.fit()` only supports the `CombinedLoader(mode="sequential")` mode.
      File "/home/art/mydir/dev/aisc_2023/Inducing-human-like-biases-in-moral-reasoning-LLMs/src/main.py", line 45, in train
        trainer.fit(lit_model, data_module)
      File "/home/art/mydir/dev/aisc_2023/Inducing-human-like-biases-in-moral-reasoning-LLMs/src/main.py", line 64, in <module>
        train(context)
    ValueError: `trainer.fit()` only supports the `CombinedLoader(mode="sequential")` mode.

So next revert back to using dataloader_idx and retrieve ds_cfg from cached array. This is headache.